service: backupmongo

provider:
  name: aws
  stage: production
  runtime: nodejs8.10
  environment:
    MONGO_URL: "{MONGO_URI}"
    S3_PATH: "{S3_PATH}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::{S3_NAME}/*"
      

functions:
  backup:
    handler: handler.backup
    events:
      - schedule: cron(25 * * * ? *) # Every hour at minute 25
